name: Deploy to AWS ASG

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  DOCKER_IMAGE: augusto573/app-hello-world

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # 1. Login y Push a DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

    # 2. Configurar Credenciales AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    # 3. Instalar Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # 4. Terraform Init
    - name: Terraform Init
      run: terraform init

    # 5. Terraform Apply (Actualizando la Infraestructura)
    # Aquí pasamos el TAG del commit actual. Esto cambia el Launch Template
    # y dispara el Instance Refresh del ASG.
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
        -var="docker_image=${{ env.DOCKER_IMAGE }}" \
        -var="image_tag=${{ github.sha }}"